version: "3.9"
services:
  rails:
    image: thmyrk/simple-bot:latest
    # build: .
    command: rails server -b 0.0.0.0 -p 3000
    ports:
      - "3000:3000"
    # volumes:
      # - .:/simple-bot
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - REQUIRED_TOKEN=911fd6173532136f418e3c312731e1028fce367014524cee8d0ea0a8278ac5e8

